// @ts-check

import eslint from "@eslint/js";
import { defineConfig } from "eslint/config";
import tseslint from "typescript-eslint";

export default defineConfig(
  eslint.configs.recommended,
  tseslint.configs.recommended,
  {
    // `src/gen/**` is auto-generated by `pnpm generate` (openapi-typescript)
    // and must not be hand-edited; exclude it from linting rather than tweaking
    // the generated output.
    ignores: ["lib/**", "node_modules/**", "dist/**", "src/gen/**"],
  },
);
